stages:
  - test
  - deploy

before_script:
- apt-get update
- apt-get install redis-server -y
- redis-server --daemonize yes
- python -V
- pip install tox

.test-py38:
  stage: test
  image: python:3.8-buster

test-38-django31:
  extends: .test-py38
  script:
    - tox -e py38-django31
  artifacts:
    when: always
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

deploy-pypi:
  stage: deploy
  image: python:3.8-buster

  before_script:
    - pip install twine

  script:
    - python setup.py sdist bdist_wheel
    - twine upload dist/*

  rules:
    - if: $CI_COMMIT_TAG