# Generated by Django 3.1.2 on 2021-01-13 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveuniverse', '0004_effect_longer_name'),
        ('moonstuff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraction',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='extraction',
            unique_together={('arrival_time', 'moon')},
        ),
    ]
