# Generated by Django 3.1.2 on 2021-01-22 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moonstuff', '0002_auto_20210113_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraction',
            name='depleted',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='extraction',
            name='total_volume',
            field=models.BigIntegerField(null=True),
        ),
    ]
