# Generated by Django 3.1.2 on 2021-01-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveuniverse', '0004_effect_longer_name'),
        ('moonstuff', '0003_auto_20210122_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='refinery',
            name='observer',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='extraction',
            unique_together={('start_time', 'moon')},
        ),
    ]
