# Generated by Django 3.1.2 on 2021-01-22 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveuniverse', '0004_effect_longer_name'),
        ('moonstuff', '0004_auto_20210122_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extraction',
            name='depleted',
        ),
        migrations.AddField(
            model_name='extraction',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.IntegerField()),
                ('last_updated', models.DateField()),
                ('quantity', models.BigIntegerField()),
                ('recorded_corporation_id', models.IntegerField()),
                ('evetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eveuniverse.evetype')),
                ('observer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='moonstuff.refinery')),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
