# Generated by Django 3.1.2 on 2021-03-11 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eveuniverse', '0004_effect_longer_name'),
        ('moonstuff', '0005_auto_20210122_2241'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ledgerentry',
            unique_together={('observer', 'last_updated', 'character_id', 'evetype')},
        ),
    ]
