# Generated by Django 3.1.2 on 2021-03-27 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moonstuff', '0007_auto_20210326_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraction',
            name='jackpot',
            field=models.BooleanField(default=False),
        ),
    ]
