# Generated by Django 3.1.2 on 2021-03-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moonstuff', '0008_auto_20210327_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraction',
            name='depleted',
            field=models.BooleanField(default=False),
        ),
    ]
