# Generated by Django 3.1.2 on 2021-04-18 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moonstuff', '0009_extraction_depleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moonstuff',
            options={'default_permissions': (), 'managed': False, 'permissions': (('access_moonstuff', 'Allows access to the moonstuff module'), ('access_moon_list', 'Allows access to list of all moons.'))},
        ),
    ]
